package com.lt.vu.hospital.mybatis.dao;

import com.lt.vu.hospital.mybatis.model.Doctor;
import java.util.List;

public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    int insert(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    Doctor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    List<Doctor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DOCTOR
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    int updateByPrimaryKey(Doctor record);
}