package com.lt.vu.hospital.mybatis.dao;

import com.lt.vu.hospital.mybatis.model.Hospital;
import java.util.List;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    int insert(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    Hospital selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    List<Hospital> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HOSPITAL
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    int updateByPrimaryKey(Hospital record);
}