package com.lt.vu.hospital.mybatis.model;

public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.ID
     *
     * @return the value of PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.ID
     *
     * @param id the value for PUBLIC.DOCTOR.ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DOCTOR.NAME
     *
     * @return the value of PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DOCTOR.NAME
     *
     * @param name the value for PUBLIC.DOCTOR.NAME
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}