package com.lt.vu.hospital.mybatis.model;

public class Hospital {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HOSPITAL.ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HOSPITAL.ADDRESS
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HOSPITAL.TITLE
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HOSPITAL.ID
     *
     * @return the value of PUBLIC.HOSPITAL.ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HOSPITAL.ID
     *
     * @param id the value for PUBLIC.HOSPITAL.ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HOSPITAL.ADDRESS
     *
     * @return the value of PUBLIC.HOSPITAL.ADDRESS
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HOSPITAL.ADDRESS
     *
     * @param address the value for PUBLIC.HOSPITAL.ADDRESS
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HOSPITAL.TITLE
     *
     * @return the value of PUBLIC.HOSPITAL.TITLE
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HOSPITAL.TITLE
     *
     * @param title the value for PUBLIC.HOSPITAL.TITLE
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }
}