package com.lt.vu.hospital.mybatis.model;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    private Long hospitalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.ID
     *
     * @return the value of PUBLIC.PATIENT.ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.ID
     *
     * @param id the value for PUBLIC.PATIENT.ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.NAME
     *
     * @return the value of PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.NAME
     *
     * @param name the value for PUBLIC.PATIENT.NAME
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @return the value of PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public Long getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @param hospitalId the value for PUBLIC.PATIENT.HOSPITAL_ID
     *
     * @mbg.generated Mon Apr 04 22:47:13 EEST 2022
     */
    public void setHospitalId(Long hospitalId) {
        this.hospitalId = hospitalId;
    }
}